const EmployeeList = [{
    id: "0001",
    firstname: "Robert",
    lastname: "Kyle",
    age: 45,
    position: "Manager",
    department: "Marketing",
    salary: 60000,
  },
  {
    id: "0002",
    firstname: "Erik",
    lastname: "Watkins",
    age: 30,
    department: "IT",
    salary: 50000,
  },
  {
    id: "0003",
    firstname: "Chalice",
    lastname: "Attwater",
    age: 26,
    department: "Marketing",
    salary: 44000,
  },
  {
    id: "0004",
    firstname: "Benedict",
    lastname: "Queen",
    age: 32,
    department: "Accounting",
    salary: 40000,
  },
  {
    id: "0005",
    firstname: "Metis",
    lastname: "Hale",
    age: 50,
    department: "Accounting",
    salary: 44000,
  },
  {
    id: "0006",
    firstname: "Jamshid",
    lastname: "Fux",
    age: 30,
    department: "IT",
    salary: 50000,
  },
  {
    id: "0007",
    firstname: "Cletus",
    lastname: "Schindler",
    age: 43,
    department: "Marketing",
    salary: 90000,
  }
];
export default EmployeeList;